### ISSUE TITLE
Uncaught Error: undefined is not an object (evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by tomprogers** [lwansbrough/react-native-camera#181]
I'm getting this error on simulators and on my real iPhone 5.

I followed the "mostly automatic" instructions. None of the commands threw any errors.

I'm building an app using ExponentJS, in case that's relevant. I haven't figured out how to follow the manual steps yet (I don't have an Xcode project).

**Comment by evanmrose** [comment]
+1

**Comment by tomprogers** [comment]
The problem appears to be related to the fact that projects created with ExponentJS don't come with all the Xcode and Objective-C stuff that you get when you create a new project via `react-native init [myappname]`. In this scenario, the rnpm link command listed in the README performs no work -- and shows no errors -- and this module won't function.

I don't think this project is responsible for resolving the issue, but it does seem like this module would benefit from some more aggressive error logging. I got lucky by thinking to build a new react-native project and integrate this component; at no point did this module indicate that it's dependencies weren't satisfied.

**Comment by cuitianze** [comment]
+1

**Comment by shssoichiro** [comment]
For those who may still be googling to find the answer to this, my issue was that I had not restarted XCode/rebuilt the project after installing react-native-camera. Reloading the JS isn't enough, I had to exit the simulator and restart XCode so that the native modules would build.

Hopefully this helps someone.

**Comment by jorry** [comment]
android +1

**Comment by silentcloud** [comment]
+1

**Comment by KayahanKahriman** [comment]
Im still getting this error. rnpm didnt work, tried to install manually but it didnt work either. Closed react-native packager and closed emulator (geny motion - galaxy s6) none of these didnt work. Plus, this should have been explained in more detail i think because there's no "getPackages method" there.

"Add new RCTCameraPackage() to the list returned by the getPackages() method"

**Comment by simzen85** [comment]
I'm having this error with ExponentJS, does anyone know how to solve this ? Thanks all

**Comment by Anuj-786** [comment]
hey, I got the same error in android simulator. whats is this error and how to sole it please anyone help.

**Comment by hbd** [comment]
Getting this error on 
```
react-native-cli: 1.2.0
react-native: 0.28.0
```

**Comment by stoefln** [comment]
strange thing is I am getting this error in a project where I am not even using this library :/
In my camera project everything works fine.

**Comment by stoefln** [comment]
Restarting the react server helped. Error gone!
