### ISSUE TITLE
Remove state within Camera component

### ISSUE THREAD

**Issue by amccloud** [lwansbrough/react-native-camera#22]
The Camera component should be stateless. Looking at what state is available i believe we can remove it all.

##### isAuthorized

Doesn't appear to be used.

##### aspect, type, and orientation

Derived from props, we should just use the props.

See https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html for more information.

I can contribute this change I just want to make sure you agree before I start.

**Comment by lwansbrough** [comment]
I actually just changed this while refactoring the component. See those changes here: https://github.com/lwansbrough/react-native-camera/commit/6dfcfa134e3c5411cd35768efca29e4c14f1cac6

I think the justification behind setting the `isAuthorized` state property was so that it could be read externally to determine the state of authorization, but seeing as it's set within an async call there isn't much use in that.
