### ISSUE TITLE
ios 10 - app crashes when view with <Camera> is rendered

### ISSUE THREAD

**Issue by romanmandryk** [lwansbrough/react-native-camera#386]
react-native-camera crashes the iOS app when built in XCode 8 beta running on ios 10 simulator.
Same code works fine when built with XCode 7 and runs on iOS 9.3.
### Steps to reproduce
1. Install react-native-camera as described in README
2. In Info.plist set NSCameraUsageDescription to any value (required in ios 10)
3. create a sample view with Camera tag
### Expected behaviour

Camera preview should open
### Actual behaviour

After navigating to the view with Camera tag
the app crashes with EXC_BAD_ACCESS. XCode stops in RCTCameraManager.m:34
   self.previewLayer = [AVCaptureVideoPreviewLayer layerWithSession:self.session];
### Environment
- **Node.js version**: 4.4.5
- **React Native version**: 0.31
- **React Native platform + platform version**: iOS 10.0 simulator, XCode 8 beta
### react-native-camera

**Version**: latest  "master" (29 Aug 2016)
### Note

I tried to downgrade to npm version of react-native-camera (0.38) and the app crashes immediately after start (also in RCTCameraManager.m in init method)

Any ideas how to fix this or at least how to debug it?

**Comment by nitrogenlabs** [comment]
Running into the same prob.

Environment:

- NodeJS: 6.5.0
- React Native: 0.33
- XCode: 8.0 (8A218a)

**Comment by derdav3** [comment]
Had the same, but deleting the build folder, restarting the server with `react-native start -- --reset-cache` solved it

**Comment by nitrog7** [comment]
Just to clarify, you have to also use the master branch, not 0.3.8.

**Comment by ibussieres** [comment]
I can't get it to work, even with the proposed workaround.

**Comment by nitrog7** [comment]
You'll also have to comment out a few lines for the preview on simulator in the initial view. With the master branch, in RCTCameraManager.m (line 30) update the following:

```
- (UIView *)view
{
  self.session = [AVCaptureSession new];
    
#if !(TARGET_IPHONE_SIMULATOR)
  self.previewLayer = [AVCaptureVideoPreviewLayer layerWithSession:self.session];
  self.previewLayer.needsDisplayOnBoundsChange = YES;
#endif
    
  return [[RCTCamera alloc] initWithManager:self bridge:self.bridge];
}
```

Or you can just use a modified fork until the main branch is updated at: https://www.npmjs.com/package/@nitrog7/react-native-camera

`npm install --save @nitrog7/react-native-camera`

**Comment by dijonkitchen** [comment]
On the stable release of Xcode 8, I edited the Info.plist for NSCameraUsageDescription as mentioned here: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW24

After just adding the #if and #endif lines to the RCTCameraManager.m file as noted by @nitrog7 and restarting React server, the camera works and doesn't crash on use. 

I didn't have to use master instead of 0.3.8 of react-native-camera.

**Comment by rgoldiez** [comment]
Crashing on iPhone 7 w/ iOS 10.  My app was working fine on iPhone 6s w/ iOS 10.

**Comment by derdav3** [comment]
error code? @rgoldiez

**Comment by nitrogenlabs** [comment]
Thanks, I’m still hoping there is a better solution than to comment out but looking back at my code, I have the NSCameraUsageDescription set and was still getting the error. Not sure if it was because if a beta version of XCode (it shouldn’t be, since I’m on 8A218a) or if there is a cache that has not cleared.

Using the master branch does resolve errors for use with React-Native 0.33 and React 15.3.1.

**Comment by rgoldiez** [comment]
@derdav3 - Unfortunately I can't (or don't know how) to run in debug on my device right now as I am at a conference on wifi that blocks traffic to other clients.  I will have to try in debug mode when I get home tonight/tomorrow.

**Comment by dijonkitchen** [comment]
@nitrogenlabs it may be because of the beta, try the stable release. 

@rgoldiez if you click on your project name in Xcode, you'll see "Edit scheme" then there's a drop down for release or debug.

**Comment by rgoldiez** [comment]
@nitrogenlabs - Please see the screenshot below regarding the crash once the camera loads.  It had been crashing in the simulator, but adding the #if/#endif bypassing where the simulator was crashing, when running in the simulator (the crash in the simulator seems more informative than the screenshot below).

![image](https://cloud.githubusercontent.com/assets/10797610/18620258/3e9c278c-7dd4-11e6-8f83-eb445c5ec667.png)

@dijonkitchen - Thanks ... my issue wasn't know how to run in debug mode... it was that I was at a conference and the wifi did not allow connections to peer clients (ie, running on my device in debut mode and pulling the JS bundle from my laptop).

**Comment by rgoldiez** [comment]
Here's the crash in the simulator, when I comment out the #if/#endif that this thread suggested adding to avoid the crash in the simulator.

![image](https://cloud.githubusercontent.com/assets/10797610/18620302/061db2d0-7dd5-11e6-9dda-de15156039e4.png)

**Comment by dijonkitchen** [comment]
I didn't actually comment them out with "//'s", I just added those lines 34 and 37 since they weren't there originally. Don't forget to restart React server too. 

When you see the signal SIGABRT error, check your Xcode logs for a detailed response. Don't forget to set the NSCameraUsageDescription in Info.plist as noted above: https://github.com/lwansbrough/react-native-camera/issues/386#issuecomment-247786699

**Comment by rgoldiez** [comment]
@dijonkitchen - I added the // comments to show the error in the simulator.  It's crashing at the same point on my iPhone 7 / iOS 10, but with seemingly less useful logs when running on the device.  Maybe unrelated.  

I'll check the Xcode logs for more details.  Also, I already had NSCameraUsageDescription in my info.plist, required now to get a build thru test flight.

**Comment by rgoldiez** [comment]
@derdav3 - Any ideas from the screenshots I posted?

**Comment by ioannagian** [comment]
@rgoldiez I had the exact same issue and was fixed by adding the two lines as @nitrog7 suggested. They are not comments, they are not to be commented out with "//" !

**Comment by rgoldiez** [comment]
@ioannagian --- I **know** they are not comments.  I **only** added the // to the simulator so show the failure in the simulator.  My issue is that the camera component is now crashing **on the actual phone**.  Commenting out this code in the simulator prevents the simulator from crashing.  It still crashes on the phone.

I've been using this component for 6 months without issue.  Only noticed it recently on my iPhone 7.

**Comment by nitrog7** [comment]
@rgoldiez Will be able to play around with it on an iPhone 7 later this week. Currently testing on the iPhone 6s. Looking at the change log, I've noticed a lot of small changes to the camera API. May need to update a couple more attributes or defaults

**Comment by rgoldiez** [comment]
Thank you @nitrog7 !!

**Comment by jasongaare** [comment]
Having the same issue. Running iOS 10 on an iPhone 6. 

My issue is when I build a release on my device, the app works as expected until the application is terminated (double tap home, dismiss app). Then on each subsequent launch the app crashes during launch. When I comment out the lines

`self.previewLayer = [AVCaptureVideoPreviewLayer layerWithSession:self.session];
  self.previewLayer.needsDisplayOnBoundsChange = YES;`

the application launches, but (obviously) the camera doesn't work.

**Comment by zhipengbird** [comment]
Add to your Info.plist:

```
<key>NSCameraUsageDescription</key>
<string>Allow us to scan documents and capture images.</string>
```

**Comment by rgoldiez** [comment]
@zhipengbird - Already have `NSCameraUsageDescription` in Info.plist.  That's not why it's crashing.

**Comment by jasongaare** [comment]
Ends up my error is not iOS 10 specific - I am getting the same crash on iOS 9. Back to the drawing board...

**Comment by kLkA** [comment]
Hey guys, any plans when will be release fixing this issue? `NSCameraUsageDescription` in info.plist not helps

**Comment by dijonkitchen** [comment]
I've been running it again and could it be the microphone access? In Chrome DevTools, it says microphone is in use when the camera pulls up. 

In Xcode I get this error too: 

> This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by rgoldiez** [comment]
@ronaldheft - Not sure about a PR but commenting out those lines (or sticking and #if / #endif around them) doesn't fix the problem on an actual device.

**Comment by rgoldiez** [comment]
@dijonkitchen - Good find... the NSMicrophoneUsageDescription setting allows the camera to run on my actual device (at least so far, in debug mode)!

Here's the part I don't like.... one of my app is using this camera component **ONLY** for scanning bar codes.  I can see some users being skeptical why barcode functionality requires access to the mic.  Seems to me that this component should only require access to the mic if you are using video mode (or both camera and video) when you launch `<Camera />`.

**Comment by dijonkitchen** [comment]
@rgoldiez agreed! Not sure where that is in the source code, but you're welcome to make a pull request that doesn't require that.

**Comment by rgoldiez** [comment]
@dijonkitchen - Thanks very kind of you to believe that I understand the Obj C / Swift side of things!  I'll be waiting until someone much smarter than me figures out how to fix this.  

Thank you for the fix for now!

**Comment by jasongaare** [comment]
@dijonkitchen @rgoldiez  I've had issues with the camera asking for microphone a lot in using this library with iOS. Whenever I use it I always include `captureAudio={false}` in my props for the `<Camera>` component. Hope this helps. 

(I'm still having this issue even with an NSMicrophoneUsageDescription)

**Comment by sscaff1** [comment]
I think this just needs to be added to the Info.plist for the app.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW1

Scroll down to where it describes NSMicrophoneUsageDescription and it states:

> Important: To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses any of the device’s microphones, must statically declare the intent to do so. Include the NSMicrophoneUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access any of the device’s microphones without a corresponding purpose string, your app exits.

I don't think this is a bug with the repo necessarily.

**Comment by kLkA** [comment]
I've added NSMicrophone too and camera started work. Thanks for comment about that :)

**Comment by bikashsharmabks** [comment]
Adding NSMicrophoneUsageDescription worked for me on iPhone but on simulator the app crashes 

So as described by @nitrog7 the work around to it for simulator is to have if else block around below block of code in RCTCameraManager.m file

```javascript
#if !(TARGET_IPHONE_SIMULATOR)
  self.previewLayer = [AVCaptureVideoPreviewLayer layerWithSession:self.session];
  self.previewLayer.needsDisplayOnBoundsChange = YES;
#endif
```

Thanks

**Comment by fud** [comment]
@bikashsharmabks Did you get issues with "        [self.session commitConfiguration];"  in the RTCameraManager.m after your change?

**Comment by bikashsharmabks** [comment]
@fud I didnt get any such issues here is what my setup looks like:

"react": "15.3.1",
"react-native": "^0.33.0",
"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git"

Below changes done for RCTCameraManager.m file
![image](https://cloud.githubusercontent.com/assets/4053186/18776546/a300cd3e-8187-11e6-886d-aeed998fe36b.png)

Thanks

**Comment by fud** [comment]
@bikashsharmabks That's exactly what I've done and installed. Mind you I could be doing something else wrong as I'm using the stock standard example mentioned in the readme and have never used this lib before.

**Comment by romanmandryk** [comment]
Confirming that after adding "if block" as posted by @nitrog7 , camera works as expected. Thank you.

**Comment by romanmandryk** [comment]
I couldn't find PR from @nitrog7 or anyone else, so created one. This fixes my original issue.

**Comment by nitrog7** [comment]
I'll add a pull request. Just wanted to make sure it was the best solution and tested.

**Comment by nitrog7** [comment]
Here ya go...
https://github.com/lwansbrough/react-native-camera/pull/424

**Comment by ibussieres** [comment]
Same problem as @fud for me, on 0.34. Bot only the second time around. iOS asks for access to the camera, I authorize, camera opens. When I come back, it crashes.

**Comment by rgoldiez** [comment]
Quick update... it seems that the`NSMicrophoneUsageDescription` is not required in Info.plist if you are only using this component as a camera **and** you `captureAudio={false}` (even tho the docs state that the setting is only applicable to video mode).

**Comment by rafayhamid2** [comment]
I have the same issue as @fud described
Did you get any solution for this?

**Comment by rgoldiez** [comment]
It's working fine for me with the NSCameraUsageDescription in my info.plist

**Comment by michaelswe** [comment]
@rgoldiez Does it also work when you invoke a camera view more than once?
Ref. issue: #426

**Comment by rgoldiez** [comment]
I'm not sure. I use <Camera /> in one spot and use it as a barcode/QR reader.

**Comment by royisch** [comment]
so what is the solution i dont understand? do i use the master and add the code or it should work? because using 0.3.8 fails to work. there are a lot of threads, could someone write the required solution? 
thanks

**Comment by ibussieres** [comment]
If you add the NSCameraUsageDescription, it should work fine on master, except for the second invocation as mentioned earlier. This is another issue, #426, that I made a pull request for a few days ago.

**Comment by scerelli** [comment]
People struggling with `SIGBRT` error must add privacy strings in xcode plist.
You have to be sure that you adding microphone permission too and not only the camera once so:

```
Privacy - Microphone Usage Description
Privacy - Camera Usage Description
```

**Comment by neilsarkar** [comment]
In case anyone coming here isn't super familiar with xcode or Info.plist, the two comments above are correct. They mean you'll want to open the project in xcode, find `Info.plist` in the file navigator, and add the string values to be displayed to the user in the permissions dialog.

<img width="1279" alt="appleclockextra_e_item-0_e_item-0_e_item-0_e_item-0_e_item-0_e_airportextra_e_displaysextra_e_applevolumeextra_e_batteryextra" src="https://cloud.githubusercontent.com/assets/83109/19215725/efde8e62-8d9d-11e6-9d48-86f28e46b8e0.png">

**Comment by royisch** [comment]
Hi @scerelli @ibussieres - im still struggling, sorry. I pulled out the master branch, meaning i installed version 0.3.8 and not 

> npm install --save lwansbrough/react-native-camera

still i get an error. Mostly i think that from all this thread i dont really understand what the issue is and what are the steps to resolve it.

![image](https://cloud.githubusercontent.com/assets/1949655/19218184/115b0940-8dfc-11e6-935d-fbfd63d3626a.png)

would be great if someone could write more descriptive steps on what should happen here.

using:
 "react": "^15.3.1"
 "react-dom": "^15.3.1"
 "react-native": "^0.33.0"
 "react-native-camera": "^0.3.8"

**Comment by jondot** [comment]
Hey Royi
Here's the summary:

Due to simulator changes as part of iOS 10 updates, the piece of code you bumped into makes it crash. It doesn't happen on device. To avoid crashing use the pragma mentioned above, or take one of the branches that include it (im on mobile so can't maneuver)

Additional issue is Apple having a refreshed permission model which now demands a special entry for each permission. Use the ones from this thread as well. It just happens that an audio permission is needed because this component does video as well, for that if you don't have video, you can disable audio capturing.
If any permission is not treated this way and you still use it - on iOS 10 your app will crash at runtime.

**Comment by royisch** [comment]
@jondot - still having issues:
here is the error:
![image](https://cloud.githubusercontent.com/assets/1949655/19219578/7283fb46-8e1f-11e6-8b16-4fce4d9c72cb.png)
here is the Plist:
![image](https://cloud.githubusercontent.com/assets/1949655/19219580/80d9719e-8e1f-11e6-9995-22a8505de63f.png)

any suggestions?

**Comment by wardnath** [comment]
@neilsarkar that fixed the issue for me, thank you

**Comment by scerelli** [comment]
@royisch you have to use `"@nitrog7/react-native-camera": "^0.3.9"` in your `package.json`, import it as `import Camera from '@nitrog7/react-native-camera'` and remember to declare in you plist permissions for microphone and camera

**Comment by kesha-antonov** [comment]
<img width="912" alt="screen shot 2016-11-12 at 16 36 48" src="https://cloud.githubusercontent.com/assets/11584712/20238202/e4e28e4a-a8f6-11e6-87d9-2e024e867048.png">

Got this error.

Have all permissions (for camera/microphone/photos)

**Comment by gabriel** [comment]
I'm also getting a BAD_ACCESS on `[self.session commitConfiguration]` line in the simulator

**Comment by abcd-ca** [comment]
In my case I couldn't reproduce the SIGABRT crash in the sim but could with an iPhone SE running 10.1.1. I added the camera AND the mic permission strings (mentioned above) in Info.plist and that worked around the problem but since I'm only taking still photos, it's suspicious why I'd be prompting the user about the mic – yes, the user sees mention of the microphone in the permission prompt. I also tried putting `captureAudio={false}` on the Camera component in my JSX code but it didn't help. Looking for a real solution now where the mic permission isn't needed – I'll start digging into the source code but let me know if someone's already solved this please.

**Comment by dijonkitchen** [comment]
I think all the original issues were solved with the merged PRs previously. 

@abcd-ca I think your problem may be related to #544.

**Comment by abcd-ca** [comment]
@dijonkitchen I upgraded from 0.5.x to 0.6.0, Removed Privacy - Microphone Usage Description but kept the camera one. I still have `captureAudio={false}` on `Camera`. Crashes on iPhone SE, 10.1.1. [Here is my crash log](https://github.com/lwansbrough/react-native-camera/files/755646/crashLog.txt)
, for what it's worth. Is 0.6.0 (via `npm install`) going to include the fixes you've alluded to? I had already manually made the required changes due to 0.40.0 with regards to the import sheme (`#import <React/foo.h>`) so it wasn't that (otherwise wouldn't have even built).

**Comment by dijonkitchen** [comment]
It should've included the changes, but I can't confirm.

**Comment by abcd-ca** [comment]
OK, I got it working. 0.6.0 works and I did have to add the `NSCameraUsageDescription` string but not the `NSMicrophoneUsageDescription` one. My mistake was that prior to rendering the component I was running `Camera.checkDeviceAuthorizationStatus` rather than `Camera. checkVideoAuthorizationStatus`. I had overlooked that subtle difference but the implication is that one would need the `NSMicrophoneUsageDescription` string for the former.

**Comment by dijonkitchen** [comment]
Wonderful, let's close this issue!

**Comment by getreup** [comment]
If anyone is reading this, when I cmd+shift+o the info.plist, I opened the wrong one and added the `NSCameraUsageDescription` there...which obviously didn't work.

**Comment by ianaa** [comment]
I had this issue only when running on a device, and turns out it was caused by setting `barCodeTypes`, as described in issues #557 and #600.
The camera view renders after removing this prop. Hope it helps someone!

**Comment by dijonkitchen** [comment]
@romanmandryk, @lwansbrough want to close this issue?

**Comment by romanmandryk** [comment]
Closing

**Comment by skathayat** [comment]
Not working! Tested with Xcode 9 Beta 2. iPhone 7Plus.
Error: 
**` @Line 448,       [metadataOutput setMetadataObjectTypes:self.barCodeTypes]; Thread 5: signal SIGABRT`**
@nitrog7

**Comment by gurudev51** [comment]
Facing exactly same issue with @skathayat

**Comment by truongthanh1303** [comment]
@neilsarkar Thanks for your info! It works fine for me 👍

**Comment by RikNieuwoudt** [comment]
What worked for me;

- Add Privacy - Photo Library Additions Usage
- Add Privacy - Photo Library Usage
- Add Privacy - Microphone Usage
- Add Privacy - Camera Usage

**Comment by haofeng123** [comment]
@jslaunch  I also met you this problem    How do you solve    thank you

**Comment by isaaclem** [comment]
@RikNieuwoudt : After added all the privacy as you've listed, the crashing does seems to be decreased a lot, however I'm still facing the same issue if I constantly keep scanning and switching back and forth between scanning and normalscreen

**Comment by n1ru4l** [comment]
`Camera` is deprecated. Please use `RNCamera` instead.
